<?php

// file_name|onmouseover_image|alt_attribute|additional_attribute

$navi=array();

$navi['smile']='smile.png||'.$lang['smilies'].'|onmouseover="q08(this,7)" onmouseout="q08(this,10)"';     // smilies
$navi['tzone']='tzone.png||'.$lang['timezone'].'|onmouseover="q08(this,7)" onmouseout="q08(this,10)"';    // timezone
$navi['sound']='sound.png||'.$lang['sound'].'|onmouseover="q08(this,7)" onmouseout="q08(this,10)"';       // sound
$navi['color']='color.png||'.$lang['color'].'|onmouseover="q08(this,7)" onmouseout="q08(this,10)"';       // colors
$navi['exitt']='exitt.png||'.$lang['exitt'].'|onmouseover="q08(this,7)" onmouseout="q08(this,10)"';       // logout

?>